#!/bin/bash
#
# CruftCleaner -- deletes files within specified directories based on a maximum age. Idea from "Mind Performance Hacks" by Ron Hale-Evans.
#

# Temporary folders to clean based on $maxage. Array in the form of: dirs=( "/fsroot/dir1/" "/fsroot/dir2/" )
dirs=( "/home/user/tmp/downloads/web/" )

# Maximum age of files in days
maxage="3"


###### Configuration ends here ######

# Initialize variables
unset dirnum

# Iterate through each element in the dirs() array
for (( dirnum=0; dirnum<${#dirs[*]}; dirnum++ ))
do

    curDir="${dirs[$dirnum]}"

    echo "Cleaning ${curDir} based on a maximum file age of ${maxage} days."

    # Find all stale files and folders in the currently selected folder more than $maxage days old
    # Using -P just to be certain find does not follow symlinks. paranoia.
    find -P "${curDir}" -ctime +${maxage} -delete

done
