#!/bin/bash
#
# CruftCleaner -- deletes files within specified folders based on a maximum age. Idea from "Mind Performance Hacks" by Ron Hale-Evans.
#

# Temporary folders to clean based on $maxage. Array in the form of: folders=( "/fsroot/folder1/" "/fsroot/folder2/" )
folders=( "/home/user/tmp/downloads/web/" )

# Maximum age of files in days
maxage="3"


###### Configuration ends here ######

# Initialize variables
unset foldernum

# Iterate through each element in the folders() array
for (( foldernum=0; foldernum<${#folders[*]}; foldernum++ ))
do

    curFolder="${folders[$foldernum]}"

    echo "Cleaning ${curFolder} based on a maximum file age of ${maxage} days."

    # Find all stale files and folders in the currently selected folder more than $maxage days old
    # Using -P just to be certain find does not follow symlinks. paranoia.
    find -P "${curFolder}" -ctime +${maxage} -delete

done
